name: Deploy to Self Hosted

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Runner Information
        run: |
          echo "Runner is working!"
          hostname
          pwd

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build
      - name: Deploy Build Files
        shell: powershell
        run: |
          $destination = "C:\deploy\training-intern"

          if (!(Test-Path $destination)) {
            New-Item -ItemType Directory -Path $destination | Out-Null
          }

          Remove-Item "$destination\*" -Recurse -Force -ErrorAction SilentlyContinue

          Copy-Item -Path "dist\*" -Destination $destination -Recurse -Force

      - name: Start or Restart PM2
        shell: powershell
        run: |
          $app = pm2 jlist | ConvertFrom-Json | Where-Object { $_.name -eq "training-intern" }

          if ($app) {
            Write-Host "Restarting PM2..."
            pm2 restart training-intern
          }
          else {
            Write-Host "Starting PM2..."
            pm2 start ecosystem.config.cjs
          }

          pm2 save 